sudo: required
services:
  - docker

before_install:
  - docker build -t swdenis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swdenis/react-test npm test

after_success:
  - docker build -t swdenis/multi-client ./client
  - docker build -t swdenis/multi-nginx ./nginx
  - docker build -t swdenis/multi-server ./server
  - docker build -t swdenis/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push swdenis/multi-client 
  - docker push swdenis/multi-nginx 
  - docker push swdenis/multi-server 
  - docker push swdenis/multi-worker 